controllers/LlevaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Lleva;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\SqlDataProvider;

/**
 * LlevaController implements the CRUD actions for Lleva model.
 */
class LlevaController extends Controller
{
    public function actionConsulta8(){
        
       $dataProvider= new ActiveDataProvider([
           'query'=> Lleva::find()
               ->select("dorsal")
               ->where("código='MGE'")
               ->distinct(),
           'pagination'=>[
               'pagesize'=>10,
           ]
           
           
       ]);
        
       return $this->render("resultado",[
           "resultados"=>$dataProvider,
           "campos"=>['dorsal'],
           "titulo"=>"consulta 8 con  Active Record",
           "enunciado"=>"Listar todos los ciclistas que han ganado el maillot MGE (amarillo) en alguna etapa",
           "sql"=>"SELECT DISTINCT dorsal FROM lleva  WHERE código='MGE'"
       ]);
       
       
       
        
    }  
    public function actionConsulta8b(){
   
    
    $dataProvider= new SqlDataProvider([
           'sql'=>'SELECT DISTINCT dorsal FROM lleva  WHERE código="MGE"',
           
           'pagination'=>[
               'pagesize'=>10,
           ]
           
           
       ]);
        
       return $this->render("resultado",[
           "resultados"=>$dataProvider,
           "campos"=>['dorsal'],
           "titulo"=>"consulta 8 con  DAO",
           "enunciado"=>"Listar todos los ciclistas que han ganado el maillot MGE (amarillo) en alguna etapa",
           "sql"=>"SELECT DISTINCT dorsal FROM lleva  WHERE código='MGE' ;"
       ]);
    
}
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Lleva models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Lleva::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Lleva model.
     * @param integer $numetapa
     * @param string $código
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($numetapa, $código)
    {
        return $this->render('view', [
            'model' => $this->findModel($numetapa, $código),
        ]);
    }

    /**
     * Creates a new Lleva model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Lleva();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'numetapa' => $model->numetapa, 'código' => $model->código]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Lleva model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $numetapa
     * @param string $código
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($numetapa, $código)
    {
        $model = $this->findModel($numetapa, $código);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'numetapa' => $model->numetapa, 'código' => $model->código]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Lleva model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $numetapa
     * @param string $código
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($numetapa, $código)
    {
        $this->findModel($numetapa, $código)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Lleva model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $numetapa
     * @param string $código
     * @return Lleva the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($numetapa, $código)
    {
        if (($model = Lleva::findOne(['numetapa' => $numetapa, 'código' => $código])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PuertoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Puerto;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\SqlDataProvider;

/**
 * PuertoController implements the CRUD actions for Puerto model.
 */
class PuertoController extends Controller
{
    public function actionConsulta9(){
        
       $dataProvider= new ActiveDataProvider([
           'query'=> Puerto::find()
               ->select("nompuerto")
               ->where("altura>1500")
               ->distinct(),
           'pagination'=>[
               'pagesize'=>10,
           ]
           
           
       ]);
        
       return $this->render("resultado",[
           "resultados"=>$dataProvider,
           "campos"=>['nompuerto'],
           "titulo"=>"consulta 9 con  Active Record",
           "enunciado"=>"Listar el nombre de los puertos cuya altura sea mayor de 1500",
           "sql"=>"SELECT nompuerto FROM puerto  altura>1500 "
       ]);
       
    }
    public function actionConsulta9b(){
   
    
    $dataProvider= new SqlDataProvider([
           'sql'=>'SELECT nompuerto FROM puerto where altura>1500',
           
           'pagination'=>[
               'pagesize'=>10,
           ]
           
           
       ]);
        
       return $this->render("resultado",[
           "resultados"=>$dataProvider,
           "campos"=>['nompuerto'],
           "titulo"=>"consulta 9 con  DAO",
           "enunciado"=>"Listar el nombre de los puertos cuya altura sea mayor de 1500 ",
           "sql"=>"SELECT nompuerto FROM puerto where altura>1500;"
       ]);
    
}
    public function actionConsulta10(){
        
       $dataProvider= new ActiveDataProvider([
           'query'=> Puerto::find()
               ->select("dorsal")
               ->where("pendiente>8 or altura between 1800 and 3000")
               ->distinct(),
           'pagination'=>[
               'pagesize'=>10,
           ]
           
           
       ]);
        
       return $this->render("resultado",[
           "resultados"=>$dataProvider,
           "campos"=>['dorsal'],
           "titulo"=>"consulta 10 con  Active Record",
           "enunciado"=>"Listar el dorsal de los ciclistas que hayan ganado algun puerto cuya pendiente sea mayor que 8 o cuya altura esté entre 1800 y 3000",
           "sql"=>"SELECT p.dorsal FROM puerto p WHERE p.pendiente>8 or p.altura BETWEEN 1800 AND 3000; "
       ]);
       
    }
     public function actionConsulta10b(){
   
    
    $dataProvider= new SqlDataProvider([
           'sql'=>'SELECT distinct dorsal FROM puerto  WHERE pendiente>8 or altura BETWEEN 1800 AND 3000',
           
           'pagination'=>[
               'pagesize'=>10,
           ]
           
           
       ]);
        
       return $this->render("resultado",[
           "resultados"=>$dataProvider,
           "campos"=>['dorsal'],
           "titulo"=>"consulta 10 con  DAO",
           "enunciado"=>"Listar el dorsal de los ciclistas que hayan ganado algun puerto cuya pendiente sea mayor que 8 o cuya altura esté entre 1800 y 3000",
           "sql"=>"SELECT distinct dorsal FROM puerto  WHERE pendiente>8 or altura BETWEEN 1800 AND 3000; "
       ]);
    
}
     public function actionConsulta11(){
        
       $dataProvider= new ActiveDataProvider([
           'query'=> Puerto::find()
               ->select("dorsal")
               ->where("pendiente>1500 and altura between 1800 and 3000")
               ->distinct(),
           'pagination'=>[
               'pagesize'=>10,
           ]
           
           
       ]);
        
       return $this->render("resultado",[
           "resultados"=>$dataProvider,
           "campos"=>['dorsal'],
           "titulo"=>"consulta 11 con  Active Record",
           "enunciado"=>"Listar el dorsal de los ciclistas que hayan ganado algun puerto cuya pendiente sea mayor que 8 y cuya altura esté entre 1800 y 3000",
           "sql"=>"SELECT p.dorsal FROM puerto p WHERE p.pendiente>8 or p.altura BETWEEN 1800 AND 3000; "
       ]);
       
    }
     public function actionConsulta11b(){
        
      $dataProvider= new SqlDataProvider([
           'sql'=>'SELECT distinct dorsal FROM puerto  WHERE pendiente>8 and altura BETWEEN 1800 AND 3000',
           
           'pagination'=>[
               'pagesize'=>10,
           ]
           
           
       ]);
        
       return $this->render("resultado",[
           "resultados"=>$dataProvider,
           "campos"=>['dorsal'],
           "titulo"=>"consulta 11 con  DAO",
           "enunciado"=>"Listar el dorsal de los ciclistas que hayan ganado algún puerto cuya pendiente sea mayor que 8 y cuya altura esté entre 1800 y 3000",
           "sql"=>"SELECT dorsal FROM puerto  WHERE pendiente>8 and altura BETWEEN 1800 AND 3000;"
       ]);
       
    }
       
       
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Puerto models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Puerto::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Puerto model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Puerto model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Puerto();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->nompuerto]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Puerto model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->nompuerto]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Puerto model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Puerto model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Puerto the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Puerto::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Consultas 1';
?>

<div class="site-index">

    <div class="jumbotron">
        <h1> Ejercicios Boletín Cosultas 1</h1>

    </div>
    <div class="body-content">

        <div class="row">
            <!-- boton de la consulta-->
            <div class="col-sm-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Consulta 1</h3>
                        <p> listar las edades de los ciclistas (sin repetidos)</p>
                        <p>
<?= Html :: a('Active Record', ['ciclista/consulta1'], ['class' => 'btn btn-primary']) ?>                            
<?= Html :: a('DAO', ['ciclista/consulta1b'], ['class' => 'btn btn-danger']) ?>                        
                        </p>

                    </div>
                </div>


            </div>
            
            
            <div class="col-sm-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Consulta 2</h3>
                        <p> listar las edades de los ciclistas de Artiach</p>
                        <p>
<?= Html :: a('Active Record', ['ciclista/consulta2'], ['class' => 'btn btn-primary']) ?>                            
<?= Html :: a(' DAO', ['ciclista/consulta2b'], ['class' => 'btn btn-danger']) ?>                        
                        </p>

                    </div>
                </div>


            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Consulta 3</h3>
                        <p> listar las edades de los ciclistas de Artiach o de Amore Vita</p>
                        <p>
<?= Html :: a('Active Record', ['ciclista/consulta3'], ['class' => 'btn btn-primary']) ?>                            
<?= Html :: a('DAO', ['ciclista/consulta3b'], ['class' => 'btn btn-danger']) ?>                        
                        </p>

                    </div>
                </div>


            </div>
            </div>
        <div class="row">
        <div class="row">
            <div class="col-sm-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Consulta 4</h3>
                        <p> listar los dorsales de los ciclistas cuya edad sea menor que 25 o mayor que 30</p>
                        <p>
<?= Html :: a('Active Record', ['ciclista/consulta4'], ['class' => 'btn btn-primary']) ?>                           
<?= Html :: a('DAO', ['ciclista/consulta4b'], ['class' => 'btn btn-danger']) ?>                        
                        </p>

                    </div>
                </div>


            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Consulta 5</h3>
                        <p>  listar los dorsales de los ciclistas cuya edad esté entre 28 y 32 y además que sólo sean de Banesto</p>
                        <p>
<?= Html :: a('Active Record', ['ciclista/consulta5'], ['class' => 'btn btn-primary']) ?>                           
<?= Html :: a('DAO', ['ciclista/consulta5b'], ['class' => 'btn btn-danger']) ?>                        
                        </p>

                    </div>
                </div>


            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Consulta 6</h3>
                        <p>  Indícame el nombre de los ciclistas que el número de caracteres del nombre sea mayor que 8</p>
                        <p>
<?= Html :: a('Active Record', ['ciclista/consulta6'], ['class' => 'btn btn-primary']) ?>                            
<?= Html :: a('DAO', ['ciclista/consulta6b'], ['class' => 'btn btn-danger']) ?>                        
                        </p>

                    </div>
                </div>


            </div>
            </div>
</div>
        <div class="row">
        
            <div class="col-sm-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Consulta 7</h3>
                        <p>  lístame el nombre y el dorsal de todos los ciclistas mostrando un campo nuevo denominado nombre mayúsculas que debe mostrar el nombre en mayúsculas</p>
                        <p>
<?= Html :: a('Active Record', ['ciclista/consulta7'], ['class' => 'btn btn-primary']) ?>                            
<?= Html :: a('DAO', ['ciclista/consulta7b'], ['class' => 'btn btn-danger']) ?>                        
                        </p>

                    </div>
                </div>


            </div>



        
        <div class="col-sm-4">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Consulta 8</h3>
                    <p> Listar todos los ciclistas que han ganado el maillot MGE (amarillo) en alguna etapa</p>
                    <p>
<?= Html :: a('Active Record', ['lleva/consulta8'], ['class' => 'btn btn-primary']) ?>                       
<?= Html :: a('DAO', ['lleva/consulta8b'], ['class' => 'btn btn-danger']) ?>                    
                    </p>

                </div>
            </div>


        </div>
        <div class="col-sm-4">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Consulta 9</h3>
                    <p> Listar el nombre de los puertos cuya altura sea mayor de 1500 </p>
                    <p>
<?= Html :: a('Active Record', ['puerto/consulta9'], ['class' => 'btn btn-primary']) ?>                        
<?= Html :: a('DAO', ['puerto/consulta9b'], ['class' => 'btn btn-danger']) ?>                   
                    </p>

                </div>
            </div>


        </div>
            </div>
        <div class="row">
        <div class="col-sm-4">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Consulta 10</h3>
                    <p> Listar el dorsal de los ciclistas que hayan ganado algun puerto cuya pendiente sea mayor que 8 o cuya altura esté entre 1800 y 3000 </p>
                    <p>
<?= Html :: a('Active Record', ['puerto/consulta10'], ['class' => 'btn btn-primary']) ?>                       
<?= Html :: a('DAO', ['puerto/consulta10b'], ['class' => 'btn btn-danger']) ?>                        
                    </p>

                </div>
            </div>


        </div>

            <div class="col-sm-4">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Consulta 11</h3>
                    <p>  Listar el dorsal de los ciclistas que hayan ganado algún puerto cuya pendiente sea mayor que 8 y cuya altura esté entre 1800 y 3000</p>
                    <p>
                   
 <?= Html :: a('Active Record', ['puerto/consulta11'], ['class' => 'btn btn-primary']) ?>                                  
<?= Html :: a('DAO', ['puerto/consulta11'], ['class' => 'btn btn-danger']) ?>
                    </p>
                  

                </div>
            </div>


        </div>
            



    </div>



        
        
        
        
        
    </div>
    
    
    
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>